config/routes.rb
IndividualProject::Application.routes.draw do
  get "home/index"
  get "report/completed"
  get "find_by_phone/index"
  resources :specialist_statuses

  resources :time_slots

  resources :statuses

  resources :appointments do
    collection do
      get 'patient/:patient_id', :action => 'new_appointment_from_patient'
    end
  end

  resources :specialists do
    collection do
      get 'manage_appointments'
    end
  end

  resources :insurances

  resources :diagnostic_codes

  resources :patients

  get '/availableSlots/:specialist_id/:date' => 'time_slots#availableSlots'

  get '/cancelAppointment/:appointment_id' => 'appointments#cancelAppointment'

  get '/find_by_phone/:phone' => 'find_by_phone#findByPhone'

  get '/amountFromCode/:codeID' => 'diagnostic_codes#getAmount'

   root 'home#index'

end

app/models/specialist.rb
class Specialist < ActiveRecord::Base
  has_many :appointments
  has_many :patients, through: :appointments
  belongs_to :specialist_status
  validates :specialist_status_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  paginates_per 10
  def full_name
    first_name + ' ' + last_name
  end

  def self.allActive
    Specialist.where("specialist_status_id=?",1)
  end

  def numAppsLeftToday
    @specialist.appointments.where("status_id=? AND date=?",1,Date.today).count
  end
end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  before_action :set_specialist, only: [:show, :edit, :update, :destroy]

  # GET /specialists
  # GET /specialists.json

  def manage_appointments
    @specialists = Specialist.where("specialist_status_id=?",1).page(params[:page])
  end

  def index
    @specialists = Specialist.all.page(params[:page])
  end

  # GET /specialists/1
  # GET /specialists/1.json
  def show
  end


  # GET /specialists/new
  def new
    @specialist = Specialist.new
  end

  # GET /specialists/1/edit
  def edit
  end

  # POST /specialists
  # POST /specialists.json
  def create
    @specialist = Specialist.new(specialist_params)

    respond_to do |format|
      if @specialist.save
        format.html { redirect_to @specialist, notice: 'Specialist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @specialist }
      else
        format.html { render action: 'new' }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialists/1
  # PATCH/PUT /specialists/1.json
  def update
    respond_to do |format|
      if @specialist.update(specialist_params)
        format.html { redirect_to @specialist, notice: 'Specialist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialists/1
  # DELETE /specialists/1.json
  def destroy
    @specialist.destroy
    respond_to do |format|
      format.html { redirect_to specialists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialist
      @specialist = Specialist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialist_params
      params.require(:specialist).permit(:first_name, :last_name, :address, :phone, :specialist_status_id)
    end
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/views/specialists/_form.html.erb
<%= form_for @specialist, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @specialist.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">

            <%= pluralize(@specialist.errors.count, "error") %> prohibited this specialist from being saved:
          </div>

          <ul>
            <% @specialist.errors.full_messages.each do |message| %>
                <li class="alert alert-danger"><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field' %>
    </div>
  </div>
    <div class="control-group">
      <%= f.label :specialist_status_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select :specialist_status_id,SpecialistStatus.all,:id,:name %>
      </div>
    </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                specialists_path, :class => 'btn' %>
  </div>
<% end %>

app/views/specialists/edit.html.erb
<%- model_class = Specialist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/specialists/index.html.erb
<%- model_class = Specialist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= paginate @specialists %>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:specialist_status_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @specialists.each do |specialist| %>
      <tr>

        <td><%= specialist.first_name %></td>
        <td><%= specialist.last_name %></td>
        <td><%= specialist.address %></td>
        <td><%= specialist.phone %></td>
        <td><%= specialist.specialist_status.name %></td>
        <td><%=l specialist.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_specialist_path(specialist), :class => 'btn btn-mini' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_specialist_path,
            :class => 'btn btn-primary' %>

app/views/specialists/manage_appointments.erb
<%- model_class = Specialist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= paginate @specialists %>
<table class="table table-striped">
  <thead>
  <tr>

    <th><%= model_class.human_attribute_name(:full_name) %></th>
    <th><%= model_class.human_attribute_name(:address) %></th>
    <th><%= model_class.human_attribute_name(:phone) %></th>
    <th><%= model_class.human_attribute_name(:number_of_scheduled_appointments_today) %></th>



  </tr>
  </thead>
  <tbody>
  <% @specialists.each do |specialist| %>
      <tr>
        <td><%= link_to specialist.full_name, specialist_path(specialist) %></td>
        <td><%= specialist.address %></td>
        <td><%= specialist.phone %></td>

        <td><%= specialist.appointments.where("status_id=? AND date=?",1,Date.today).count %></td>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/specialists/new.html.erb
<%- model_class = Specialist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/specialists/show.html.erb
<%- model_class = Specialist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @specialist.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @specialist.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @specialist.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:specialist_status_id) %>:</strong></dt>
  <dd><%= @specialist.specialist_status.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @specialist.phone %></dd>
</dl>

<table class="table table-striped">
    <thead>
        <tr>
          <th>
            Patient
          </th>
          <th>
            Status
          </th>
          <th>
            Diagnostic code
          </th>
          <th>
            Appointment Date
          </th>
          <th>
            Time slot
          </th>
          <th>
            Reason
          </th>
          <th>
            Amount
          </th>
          <th>
            Actions
          </th>
        </tr>
    </thead>
    <tbody>
      <% @specialist.appointments.each do |appointment| %>
        <tr>
          <td><%= appointment.patient.full_name %></td>
          <td><%= appointment.status.name %></td>
          <td>
            <% if appointment.diagnostic_code_id == nil%>
                <%= " " %>
            <% else %>
                <%= appointment.diagnostic_code.code %>
            <% end %>
          </td>
          <td><%= appointment.date %></td>
          <td><%= appointment.time_slot.slot %></td>
          <td><%= appointment.reason %></td>
          <td><%= number_to_currency(appointment.amount) %></td>
          <td><a class="btn" href="/appointments/<%= appointment.id %>/edit">Manage</a></td>
        </tr>
      <% end %>
    </tbody>
</table>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              manage_appointments_specialists_path, :class => 'btn'  %>


</div>