config/routes.rb
IndividualProject::Application.routes.draw do
  get "home/index"
  get "report/completed"
  get "find_by_phone/index"
  resources :specialist_statuses

  resources :time_slots

  resources :statuses

  resources :appointments do
    collection do
      get 'patient/:patient_id', :action => 'new_appointment_from_patient'
    end
  end

  resources :specialists do
    collection do
      get 'manage_appointments'
    end
  end

  resources :insurances

  resources :diagnostic_codes

  resources :patients

  get '/availableSlots/:specialist_id/:date' => 'time_slots#availableSlots'

  get '/cancelAppointment/:appointment_id' => 'appointments#cancelAppointment'

  get '/find_by_phone/:phone' => 'find_by_phone#findByPhone'

  get '/amountFromCode/:codeID' => 'diagnostic_codes#getAmount'

   root 'home#index'

end

app/models/diagnostic_code.rb
class DiagnosticCode < ActiveRecord::Base
  has_many :appointments
  validates :code, presence: true
  validates :description, presence: true
  validates :extra_amount, presence: true
  paginates_per 10
  def codeAndName
      code + ' - ' + description
  end
end

app/controllers/diagnostic_codes_controller.rb
class DiagnosticCodesController < ApplicationController
  before_action :set_diagnostic_code, only: [:show, :edit, :update, :destroy]

  # GET /diagnostic_codes
  # GET /diagnostic_codes.json
  def index
    @diagnostic_codes = DiagnosticCode.all.page(params[:page])
  end

  # GET /diagnostic_codes/1
  # GET /diagnostic_codes/1.json
  def show
  end

  # GET /diagnostic_codes/new
  def new
    @diagnostic_code = DiagnosticCode.new
  end

  # GET /diagnostic_codes/1/edit
  def edit
  end

  # POST /diagnostic_codes
  # POST /diagnostic_codes.json
  def create
    @diagnostic_code = DiagnosticCode.new(diagnostic_code_params)

    respond_to do |format|
      if @diagnostic_code.save
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully created.' }
        format.json { render action: 'show', status: :created, location: @diagnostic_code }
      else
        format.html { render action: 'new' }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  def getAmount
    amount = DiagnosticCode.find(params[:codeID]).extra_amount
    render json: amount
  end

  # PATCH/PUT /diagnostic_codes/1
  # PATCH/PUT /diagnostic_codes/1.json
  def update
    respond_to do |format|
      if @diagnostic_code.update(diagnostic_code_params)
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_codes/1
  # DELETE /diagnostic_codes/1.json
  def destroy
    @diagnostic_code.destroy
    respond_to do |format|
      format.html { redirect_to diagnostic_codes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostic_code
      @diagnostic_code = DiagnosticCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnostic_code_params
      params.require(:diagnostic_code).permit(:code, :description, :extra_amount)
    end
end

app/helpers/diagnostic_codes_helper.rb
module DiagnosticCodesHelper
end

app/views/diagnostic_codes/_form.html.erb
<%= form_for @diagnostic_code, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @diagnostic_code.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">

            <%= pluralize(@diagnostic_code.errors.count, "error") %> prohibited this diagnostic_code from being saved:
          </div>

          <ul>
            <% @diagnostic_code.errors.full_messages.each do |message| %>
                <li class="alert alert-danger"><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :extra_amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :extra_amount, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                diagnostic_codes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/diagnostic_codes/edit.html.erb
<%- model_class = DiagnosticCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diagnostic_codes/index.html.erb
<%- model_class = DiagnosticCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= paginate @diagnostic_codes %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:extra_amount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @diagnostic_codes.each do |diagnostic_code| %>
      <tr>
        <td><%= link_to diagnostic_code.id, diagnostic_code_path(diagnostic_code) %></td>
        <td><%= diagnostic_code.code %></td>
        <td><%= diagnostic_code.description %></td>
        <td><%= number_to_currency(diagnostic_code.extra_amount) %></td>
        <td><%=l diagnostic_code.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_diagnostic_code_path(diagnostic_code), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      diagnostic_code_path(diagnostic_code),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_diagnostic_code_path,
            :class => 'btn btn-primary' %>

app/views/diagnostic_codes/new.html.erb
<%- model_class = DiagnosticCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diagnostic_codes/show.html.erb
<%- model_class = DiagnosticCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @diagnostic_code.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @diagnostic_code.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:extra_amount) %>:</strong></dt>
  <dd><%= @diagnostic_code.extra_amount %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              diagnostic_codes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_diagnostic_code_path(@diagnostic_code), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              diagnostic_code_path(@diagnostic_code),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>