config/routes.rb
IndividualProject::Application.routes.draw do
  get "home/index"
  get "report/completed"
  get "find_by_phone/index"
  resources :specialist_statuses

  resources :time_slots

  resources :statuses

  resources :appointments do
    collection do
      get 'patient/:patient_id', :action => 'new_appointment_from_patient'
    end
  end

  resources :specialists do
    collection do
      get 'manage_appointments'
    end
  end

  resources :insurances

  resources :diagnostic_codes

  resources :patients

  get '/availableSlots/:specialist_id/:date' => 'time_slots#availableSlots'

  get '/cancelAppointment/:appointment_id' => 'appointments#cancelAppointment'

  get '/find_by_phone/:phone' => 'find_by_phone#findByPhone'

  get '/amountFromCode/:codeID' => 'diagnostic_codes#getAmount'

   root 'home#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :specialist
  belongs_to :patient
  belongs_to :diagnostic_code
  belongs_to :status
  belongs_to :time_slot
  validates :date, presence: true
  validates :time_slot_id, presence: true
  validates :status_id, presence: true
  validates :patient_id, presence: true
  validates :specialist_id, presence: true
  validates :reason, presence: true
  paginates_per 10
  # def getAmount(diagCode)
  #   @appointment.DiagnosticCode.find(diagCode).extra_amount
  # end

  def self.cancelAppointment(appointment_id)
      appointment = Appointment.find(appointment_id)
      appDateTime = DateTime.parse(appointment.date.to_s + 'T' + appointment.time_slot.slot)
      now = DateTime.now
      if (appDateTime.to_i - now.to_i)/3600 >= 8
        appointment.update(status_id: 3)
        "true"
      else
        "false"
      end
  end

  def self.completedAppointment
    Appointment.where("status_id =?", 2)
  end


end

app/models/diagnostic_code.rb
class DiagnosticCode < ActiveRecord::Base
  has_many :appointments
  validates :code, presence: true
  validates :description, presence: true
  validates :extra_amount, presence: true
  paginates_per 10
  def codeAndName
      code + ' - ' + description
  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  validates :name, presence: true
  has_many :patients
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :specialists, through: :appointments
  belongs_to :insurance
  paginates_per 20
  validates :phone, uniqueness: true, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    first_name + ' ' + last_name
  end

  def self.findByPhone(phone)
    patient = Patient.find_by(:phone => phone)
    if patient.nil?
      false
    else
      patient.id
    end

  end
end

app/models/specialist.rb
class Specialist < ActiveRecord::Base
  has_many :appointments
  has_many :patients, through: :appointments
  belongs_to :specialist_status
  validates :specialist_status_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  paginates_per 10
  def full_name
    first_name + ' ' + last_name
  end

  def self.allActive
    Specialist.where("specialist_status_id=?",1)
  end

  def numAppsLeftToday
    @specialist.appointments.where("status_id=? AND date=?",1,Date.today).count
  end
end

app/models/specialist_status.rb
class SpecialistStatus < ActiveRecord::Base
  validates :name, presence: true
  has_many :specialists
end

app/models/status.rb
class Status < ActiveRecord::Base
  validates :name, presence: true
  has_many :appointments

end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments
  validates :slot, presence: true

  def self.allAvailable(s_id, date)
    sql = "SELECT id FROM time_slots WHERE id NOT IN (SELECT id FROM time_slots WHERE id IN (SELECT time_slot_id FROM appointments WHERE specialist_id=" + s_id + " and date=\"" + date + "\" and status_id NOT IN(2,3)))"
    records_array =  ActiveRecord::Base.connection.execute(sql)
    idArray = Array.new
    records_array.each do |record|
      idArray.push(record["id"])
    end
    TimeSlot.find(idArray)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all.page(params[:page])
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end



  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @patient }
      else
        format.html { render action: 'new' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :address, :phone, :insurance_id)
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def completed
    @appointments = Appointment.completedAppointment
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/find_by_phone_helper.rb
module FindByPhoneHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/specialists_helper.rb
module SpecialistsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/home/index.html.erb
<h1 class="text-center page-header">Welcome to Dermatology Office</h1>
<p class="text-center">We open Monday to Friday from 8:00AM to 4:30PM</p>

app/views/report/completed.html.erb
<div class="page-header">
  <h1>Completed Appointments Report</h1>
</div>
<p><%= link_to "PDF Version", report_completed_path( :format => 'pdf'), :class => 'btn btn-mini' %></p>
<table class="table table-striped">
<thead>
    <tr>
      <th>
        Physician Name
      </th>
      <th>
        Patient Name
      </th>
      <th>
        Appointment Date
      </th>
      <th>
        Time
      </th>
      <th>
        Amount
      </th>
    </tr>
</thead>
<% @appointments.each do |appointment| %>
<tr>
    <td>
      <%= appointment.specialist.full_name %>
    </td>
    <td>
      <%= appointment.patient.full_name %>
    </td>
    <td>
      <%= appointment.date %>
    </td>
    <td>
      <%= appointment.time_slot.slot %>
    </td>
    <td>
      <%= number_to_currency(appointment.amount) %>
    </td>
</tr>
<% end %>
</table>

app/views/statuses/_form.html.erb
<%= form_for @status, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @status.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">

            <%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:
          </div>

          <ul>
            <% @status.errors.full_messages.each do |message| %>
                <li class="alert alert-danger"><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                statuses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/statuses/index.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= link_to status.id, status_path(status) %></td>
        <td><%= status.name %></td>
        <td><%=l status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_status_path(status), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      status_path(status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_status_path,
            :class => 'btn btn-primary' %>

app/views/statuses/new.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/statuses/show.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @status.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              statuses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_status_path(@status), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              status_path(@status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>